/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.BlockStateShape;
import fr.bretzel.minestom.utils.raytrace.OffsetType;
import fr.bretzel.minestomstates.BlockState;
import fr.bretzel.minestomstates.state.BambooLeaves;
import net.minestom.server.instance.block.Block;

public class BambooBounding extends BlockStateShape<BlockState> {

    public BambooBounding(Block alternative) {
        super(alternative);

        BambooLeaves leaves = states().get(BambooLeaves.class);

        if (leaves == BambooLeaves.LARGE) {
            set(0.1875, 0.0, 0.1875, 0.8125, 1.0, 0.8125);
        } else {
            set(0.3125, 0.0, 0.3125, 0.6875, 1.0, 0.6875);
        }
    }

    @Override
    public OffsetType getOffsetType() {
        return OffsetType.XZ;
    }
}