/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;
import fr.bretzel.minestom.utils.block.shape.shapes.Shapes;

public class BrewingStandBox extends Shapes {
    public BrewingStandBox() {
        add(new Shape(0.0625, 0, 0.0625, 0.9375, 0.125, 0.9375));
        add(new Shape(0.4375, 0.125, 0.4375, 0.5625, 0.875, 0.5625));
    }
}