/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class CampfireBounding extends Shape {
    public CampfireBounding() {
        super(0, 0, 0, 1, 0.4375, 1);
    }
}