/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class CarpetBox extends Shape {
    public CarpetBox() {
        super(0, 0, 0, 1, 0.0625, 1);
    }
}