/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.BlockStateShape;
import fr.bretzel.minestomstates.AxisBlockBlockState;
import fr.bretzel.minestomstates.state.Axis;
import net.minestom.server.instance.block.Block;

public class ChainBox extends BlockStateShape<AxisBlockBlockState> {

    public ChainBox(Block alternative) {
        super(alternative);

        if (states().getAxis() == Axis.Y) {
            set(0.40625, 0.0, 0.40625, 0.59375, 1.0, 0.59375);
        } else if (states().getAxis() == Axis.Z) {
            set(0.40625, 0.40625, 0.0, 0.59375, 0.59375, 1.0);
        } else if (states().getAxis() == Axis.X) {
            set(0.0, 0.40625, 0.40625, 1.0, 0.59375, 0.59375);
        }
    }
}