/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class ChestBox extends Shape {
    public ChestBox() {
        super(0.0625, 0, 0.0625, 0.9375, 0.875, 0.9375);
    }
}