/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class FarmlandBox extends Shape {
    public FarmlandBox() {
        super(0, 0, 0, 1, 0.9375, 1);
    }
}