/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class GrassPathBox extends Shape {
    public GrassPathBox() {
        super(0, 0, 0, 1, 0.9375, 1);
    }
}