/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class MushroomBox extends Shape {
    public MushroomBox() {
        super(0.3125, 0, 0.3125, 0.6875, 0.375, 0.6875);
    }
}