/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class PottedBox extends Shape {
    public PottedBox() {
        super(0.3125, 0, 0.3125, 0.6875, 0.375, 0.6875);
    }
}