/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class RedstoneTile extends Shape {
    public RedstoneTile() {
        super(0, 0, 0, 1, 0.125, 1);
    }
}