/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.shape.bounding;

import fr.bretzel.minestom.utils.block.shape.shapes.Shape;

public class StonecutterBox extends Shape {
    public StonecutterBox() {
        super(0, 0, 0, 1, 0.5625, 1);
    }
}