/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;


import fr.bretzel.minestom.utils.block.shapes.Shape;

public class CactusBounding extends Shape {
    public CactusBounding() {
        super(new Shape(0.0625, 0, 0.0625, 0.9375, 1, 0.9375));
    }
}