/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;


import fr.bretzel.minestom.utils.block.shapes.Shape;

public class ConduitBox extends Shape {
    public ConduitBox() {
        super(0.3125, 0.3125, 0.3125, 0.6875, 0.6875, 0.6875);
    }
}