/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class CubeBox extends Shape {
    public CubeBox() {
        super(new Shape(0, 0, 0, 1, 1, 1));
    }
}