/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class DaylightDetectorBox extends Shape {
    public DaylightDetectorBox() {
        super(0, 0, 0, 1, 0.375, 1);
    }
}