/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class DragonEggBox extends Shape {
    public DragonEggBox() {
        super(0.0625, 0, 0.0625, 0.9375, 1, 0.9375);
    }
}