/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class EnchantingTableBox extends Shape {
    public EnchantingTableBox() {
        super(0, 0, 0, 1, 0.75, 1);
    }
}