/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class HeadBox extends Shape {
    //TODO WALL HEAD
    public HeadBox() {
        super(0.25, 0, 0.25, 0.75, 0.5, 0.75);
    }
}