/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shapes;

public class LecternBounding extends Shapes {
    public LecternBounding() {
        add(0, 0, 0, 1, 0.125, 1);
        add(0.25, 0.125, 0.25, 0.75, 0.875, 0.75);
    }
}