/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class LilyPadBox extends Shape {
    public LilyPadBox() {
        super(0.0625, 0, 0.0625, 0.9375, 0.09375, 0.9375);
    }
}