/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.bounding;

import fr.bretzel.minestom.utils.block.shapes.Shape;

public class SoulSandBox extends Shape {
    public SoulSandBox() {
        super(new Shape(0, 0, 0, 1, 0.875, 1));
    }
}