package fr.bretzel.minestom.utils.instance.biomes;

import net.minestom.server.MinecraftServer;
import net.minestom.server.utils.NamespaceID;
import net.minestom.server.world.biomes.Biome;
import net.minestom.server.world.biomes.BiomeEffects;

import java.util.Arrays;

public class Biomes {

    public static Biome BADLANDS = Biome.builder().name(NamespaceID.from("minecraft:badlands")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).foliageColor(10387789).build()).build();
    public static Biome BAMBOO_JUNGLE = Biome.builder().name(NamespaceID.from("minecraft:bamboo_jungle")).temperature(0.95F).downfall(0.9F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7842047).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome BASALT_DELTAS = Biome.builder().name(NamespaceID.from("minecraft:basalt_deltas")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(6840176).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome BEACH = Biome.builder().name(NamespaceID.from("minecraft:beach")).temperature(0.8F).downfall(0.4F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome BIRCH_FOREST = Biome.builder().name(NamespaceID.from("minecraft:birch_forest")).temperature(0.6F).downfall(0.6F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8037887).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome COLD_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:cold_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4020182).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome CRIMSON_FOREST = Biome.builder().name(NamespaceID.from("minecraft:crimson_forest")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(3343107).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DARK_FOREST = Biome.builder().name(NamespaceID.from("minecraft:dark_forest")).temperature(0.7F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7972607).grassColorModifier(BiomeEffects.GrassColorModifier.DARK_FOREST).build()).build();
    public static Biome DEEP_COLD_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:deep_cold_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4020182).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DEEP_DARK = Biome.builder().name(NamespaceID.from("minecraft:deep_dark")).temperature(0.8F).downfall(0.4F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DEEP_FROZEN_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:deep_frozen_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(3750089).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DEEP_LUKEWARM_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:deep_lukewarm_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4566514).waterFogColor(267827).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DEEP_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:deep_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DESERT = Biome.builder().name(NamespaceID.from("minecraft:desert")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome DRIPSTONE_CAVES = Biome.builder().name(NamespaceID.from("minecraft:dripstone_caves")).temperature(0.8F).downfall(0.4F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome END_BARRENS = Biome.builder().name(NamespaceID.from("minecraft:end_barrens")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(10518688).waterColor(4159204).waterFogColor(329011).skyColor(0).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome END_HIGHLANDS = Biome.builder().name(NamespaceID.from("minecraft:end_highlands")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(10518688).waterColor(4159204).waterFogColor(329011).skyColor(0).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome END_MIDLANDS = Biome.builder().name(NamespaceID.from("minecraft:end_midlands")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(10518688).waterColor(4159204).waterFogColor(329011).skyColor(0).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome ERODED_BADLANDS = Biome.builder().name(NamespaceID.from("minecraft:eroded_badlands")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).foliageColor(10387789).build()).build();
    public static Biome FLOWER_FOREST = Biome.builder().name(NamespaceID.from("minecraft:flower_forest")).temperature(0.7F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7972607).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome FOREST = Biome.builder().name(NamespaceID.from("minecraft:forest")).temperature(0.7F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7972607).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome FROZEN_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:frozen_ocean")).temperature(0.0F).downfall(0.5F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(3750089).waterFogColor(329011).skyColor(8364543).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome FROZEN_PEAKS = Biome.builder().name(NamespaceID.from("minecraft:frozen_peaks")).temperature(-0.7F).downfall(0.9F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8756735).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome FROZEN_RIVER = Biome.builder().name(NamespaceID.from("minecraft:frozen_river")).temperature(0.0F).downfall(0.5F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(3750089).waterFogColor(329011).skyColor(8364543).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome GROVE = Biome.builder().name(NamespaceID.from("minecraft:grove")).temperature(-0.2F).downfall(0.8F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8495359).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome ICE_SPIKES = Biome.builder().name(NamespaceID.from("minecraft:ice_spikes")).temperature(0.0F).downfall(0.5F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8364543).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome JAGGED_PEAKS = Biome.builder().name(NamespaceID.from("minecraft:jagged_peaks")).temperature(-0.7F).downfall(0.9F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8756735).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome JUNGLE = Biome.builder().name(NamespaceID.from("minecraft:jungle")).temperature(0.95F).downfall(0.9F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7842047).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome LUKEWARM_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:lukewarm_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4566514).waterFogColor(267827).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome LUSH_CAVES = Biome.builder().name(NamespaceID.from("minecraft:lush_caves")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome MANGROVE_SWAMP = Biome.builder().name(NamespaceID.from("minecraft:mangrove_swamp")).temperature(0.8F).downfall(0.9F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(3832426).waterFogColor(5077600).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.SWAMP).foliageColor(9285927).build()).build();
    public static Biome MEADOW = Biome.builder().name(NamespaceID.from("minecraft:meadow")).temperature(0.5F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(937679).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome MUSHROOM_FIELDS = Biome.builder().name(NamespaceID.from("minecraft:mushroom_fields")).temperature(0.9F).downfall(1.0F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7842047).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome NETHER_WASTES = Biome.builder().name(NamespaceID.from("minecraft:nether_wastes")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(3344392).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome OCEAN = Biome.builder().name(NamespaceID.from("minecraft:ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome OLD_GROWTH_BIRCH_FOREST = Biome.builder().name(NamespaceID.from("minecraft:old_growth_birch_forest")).temperature(0.6F).downfall(0.6F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8037887).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome OLD_GROWTH_PINE_TAIGA = Biome.builder().name(NamespaceID.from("minecraft:old_growth_pine_taiga")).temperature(0.3F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8168447).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome OLD_GROWTH_SPRUCE_TAIGA = Biome.builder().name(NamespaceID.from("minecraft:old_growth_spruce_taiga")).temperature(0.25F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8233983).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome PLAINS = Biome.builder().name(NamespaceID.from("minecraft:plains")).temperature(0.8F).downfall(0.4F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome RIVER = Biome.builder().name(NamespaceID.from("minecraft:river")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SAVANNA = Biome.builder().name(NamespaceID.from("minecraft:savanna")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SAVANNA_PLATEAU = Biome.builder().name(NamespaceID.from("minecraft:savanna_plateau")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SMALL_END_ISLANDS = Biome.builder().name(NamespaceID.from("minecraft:small_end_islands")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(10518688).waterColor(4159204).waterFogColor(329011).skyColor(0).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SNOWY_BEACH = Biome.builder().name(NamespaceID.from("minecraft:snowy_beach")).temperature(0.05F).downfall(0.3F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4020182).waterFogColor(329011).skyColor(8364543).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SNOWY_PLAINS = Biome.builder().name(NamespaceID.from("minecraft:snowy_plains")).temperature(0.0F).downfall(0.5F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8364543).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SNOWY_SLOPES = Biome.builder().name(NamespaceID.from("minecraft:snowy_slopes")).temperature(-0.3F).downfall(0.9F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8560639).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SNOWY_TAIGA = Biome.builder().name(NamespaceID.from("minecraft:snowy_taiga")).temperature(-0.5F).downfall(0.4F).precipitation(Biome.Precipitation.SNOW).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4020182).waterFogColor(329011).skyColor(8625919).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SOUL_SAND_VALLEY = Biome.builder().name(NamespaceID.from("minecraft:soul_sand_valley")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(1787717).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SPARSE_JUNGLE = Biome.builder().name(NamespaceID.from("minecraft:sparse_jungle")).temperature(0.95F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7842047).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome STONY_PEAKS = Biome.builder().name(NamespaceID.from("minecraft:stony_peaks")).temperature(1.0F).downfall(0.3F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7776511).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome STONY_SHORE = Biome.builder().name(NamespaceID.from("minecraft:stony_shore")).temperature(0.2F).downfall(0.3F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8233727).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SUNFLOWER_PLAINS = Biome.builder().name(NamespaceID.from("minecraft:sunflower_plains")).temperature(0.8F).downfall(0.4F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome SWAMP = Biome.builder().name(NamespaceID.from("minecraft:swamp")).temperature(0.8F).downfall(0.9F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(6388580).waterFogColor(2302743).skyColor(7907327).grassColorModifier(BiomeEffects.GrassColorModifier.SWAMP).foliageColor(6975545).build()).build();
    public static Biome TAIGA = Biome.builder().name(NamespaceID.from("minecraft:taiga")).temperature(0.25F).downfall(0.8F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8233983).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome THE_END = Biome.builder().name(NamespaceID.from("minecraft:the_end")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(10518688).waterColor(4159204).waterFogColor(329011).skyColor(0).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome THE_VOID = Biome.builder().name(NamespaceID.from("minecraft:the_void")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WARM_OCEAN = Biome.builder().name(NamespaceID.from("minecraft:warm_ocean")).temperature(0.5F).downfall(0.5F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4445678).waterFogColor(270131).skyColor(8103167).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WARPED_FOREST = Biome.builder().name(NamespaceID.from("minecraft:warped_forest")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(1705242).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WINDSWEPT_FOREST = Biome.builder().name(NamespaceID.from("minecraft:windswept_forest")).temperature(0.2F).downfall(0.3F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8233727).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WINDSWEPT_GRAVELLY_HILLS = Biome.builder().name(NamespaceID.from("minecraft:windswept_gravelly_hills")).temperature(0.2F).downfall(0.3F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8233727).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WINDSWEPT_HILLS = Biome.builder().name(NamespaceID.from("minecraft:windswept_hills")).temperature(0.2F).downfall(0.3F).precipitation(Biome.Precipitation.RAIN).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(8233727).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WINDSWEPT_SAVANNA = Biome.builder().name(NamespaceID.from("minecraft:windswept_savanna")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).build()).build();
    public static Biome WOODED_BADLANDS = Biome.builder().name(NamespaceID.from("minecraft:wooded_badlands")).temperature(2.0F).downfall(0.0F).precipitation(Biome.Precipitation.NONE).effects(BiomeEffects.builder().fogColor(12638463).waterColor(4159204).waterFogColor(329011).skyColor(7254527).grassColorModifier(BiomeEffects.GrassColorModifier.NONE).foliageColor(10387789).build()).build();

    public static void init() {
        Arrays.stream(Biomes.class.getFields()).forEach(field -> {
            try {
                Biome biome = (Biome) field.get(null);
                if (MinecraftServer.getBiomeManager().getByName(biome.name()) == null)
                    MinecraftServer.getBiomeManager().addBiome(biome);
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }
        });
    }

}