/**
 * ### AUTOGENERATED ###
 */

package fr.bretzel.minestom.utils.block.visual;

import fr.bretzel.minestom.utils.block.shapes.Shapes;

public class ComposterVisual extends Shapes {
    public ComposterVisual() {
        add(0, 0, 0, 1, 0.125, 1);
        add(0, 0.125, 0, 0.125, 1, 1);
        add(0.125, 0.125, 0, 1, 1, 0.125);
        add(0.125, 0.125, 0.875, 1, 1, 1);
        add(0.875, 0.125, 0.125, 1, 1, 0.875);
    }
}